DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS ADDRESSES;

CREATE TABLE USER_DETAIL (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  EMPLOYEE_ID VARCHAR(10) UNIQUE NOT NULL,
  TITLE VARCHAR(10) NOT NULL,
  FIRST_NAME VARCHAR(40) NOT NULL,
  LAST_NAME VARCHAR(40) NOT NULL,
  GENDER VARCHAR(10),
  LAST_UPDATED_DATE_TIME TIMESTAMP
);

CREATE UNIQUE INDEX IDX_EMPLOYEE_ID ON USER_DETAIL (EMPLOYEE_ID);

CREATE TABLE ADDRESS (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  USER_ID INT UNIQUE NOT NULL,
  STREET VARCHAR(100) NOT NULL,
  CITY VARCHAR(30) NOT NULL,
  POSTCODE VARCHAR(10) NOT NULL,
  STATE VARCHAR(20),
  COUNTRY VARCHAR(20) NOT NULL,
  CONSTRAINT FK_ADDRESS_USER FOREIGN KEY (USER_ID) REFERENCES USER_DETAIL(ID)
);